# Generated by Django 5.1 on 2024-08-15 07:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_abcd"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Abcd",
        ),
    ]
