# Generated by Django 5.1 on 2024-08-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_delete_abcd"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calander",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calander", models.CharField(max_length=50)),
            ],
        ),
    ]
